#!/usr/bin/env python

import sys
import datetime

def create_contract(file, args):
	if(len(args) != 1):
		print "Must provide weekly hours for contract"
		sys.exit()

	hours = args[0]
	datestring = get_date_string()
	timestring = get_time_string()

	string = ' '.join(["CONTRACT","START",datestring,hours])
	file.write(string + "\n")

def end_contract(file, args): 
	if(len(args) != 0):
		print "Superflouous arguments"
		sys.exit()

	datestring = get_date_string()
	timestring = get_time_string()

	string = ' '.join(["CONTRACT","STOP",datestring])
	file.write(string + "\n")

def create_project(file, args):
	print "Creating Project"
	pass

def create_category(file, args):
	print "Creating category"
	pass

def start_work(file, args):
	if(len(args) != 1):
		print "Must provide description of work"
		sys.exit()

	description = args[0]
	datestring = get_date_string()
	timestring = get_time_string()

	string = ' '.join(["WORK","START",datestring,timestring,"000","000",description])
	file.write(string + "\n")

def stop_work(file, args):
	if(len(args) != 0):
		print "Superflouous arguments, quitting"
		sys.exit()

	datestring = get_date_string()
	timestring = get_time_string()

	string = ' '.join(["WORK","STOP",datestring,timestring])
	file.write(string + "\n")

def get_date_string():
	return str(datetime.datetime.now().date())

def get_time_string():
	time_info = datetime.datetime.now()
	date = str(time_info.hour).rjust(2,"0") + ":" + str(time_info.minute).rjust(2,"0")
	return date

program_name = sys.argv[0]
command = sys.argv[1]

processors = { 	"con": create_contract,
				"pro": create_project,
				"cat": create_category,
				"start": start_work,
				"stop": stop_work }

file_path = "work.dat"
file = open(file_path, "a")

processors[command](file, sys.argv[2:])

file.close()
